version: '2'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql

  web:
    build: .
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
      - DB_NAME=database
      - DB_USER=user
      - DB_PASSWORD=password
    command: >
      sh -c "./manage.py migrate &&
             ./manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    depends_on:
      - db
    volumes:
      - ./:/app

volumes:
  db-data:

